### ISSUE TITLE
Downsampling

### ISSUE THREAD

**Issue by christian-oreilly** [christian-oreilly/infant_template_paper#3]
As reported by @larsoner in email exchanges:

> The 5120-tri BEM surfaces do not have the same triangle definitions as the standard MNE ICO surface. This indicates that they were downsampled by something other than FreeSurfer routines, so some guarantees that are usually there (e.g., can be downsampled to lower ICO, normals point outward, etc.) may not be satisfied. Maybe it's worth using the FreeSurfer downsampling routines to downsample them rather than mne.decimate_surface (which uses VTK)

**Comment by larsoner** [comment]
In particular, passing `method='sphere'` to [decimate_surface](https://mne.tools/stable/generated/mne.decimate_surface.html) might take care of this issue

**Comment by christian-oreilly** [comment]
Ok. I can update and generate one sample file. Would you mind checking it with whatever code you used that failed previously?

**Comment by christian-oreilly** [comment]
... or just post a snippet of the code you used and I can check it directly if you prefer.

**Comment by larsoner** [comment]
Here is a `gist` version of the code that I attached in our emails, but with the `ico=None` line uncommented (which uses `ico=5`, which should check that it's downsampled properly):

https://gist.github.com/larsoner/72703fb3e37ae7082479c0591a4bee72

**Comment by christian-oreilly** [comment]
Thanks @larsoner for the gist. Outlook in its infinite wisdom did not allow me to check the .py file you have attached to the email so the gist will be useful. I'll look into this.

**Comment by larsoner** [comment]
Probably from a suspicious sender :)

**Comment by christian-oreilly** [comment]
The pipeline has be reran with using `method='sphere'` in `decimate_surface`. I ran you gist, uncommenting `ico=None` to that it runs `mne.write_bem_surfaces` runs with the default `ico=5`. The scripts run all the way, so I think this issue is solved. The new templates will be uploaded and this ticket closed with the next commit.

**Comment by larsoner** [comment]
Great, thanks @christian-oreilly !

**Comment by larsoner** [comment]
On d907822cdd50695838a7b03e9f50764862a83eb4 (which closed this issue) when in the `Templates` directory I still see:
```Python
>>> import mne
>>> name = 'ANTS1-0Months3T'
>>> bem = mne.make_bem_model(name, subjects_dir='.', verbose=True)
Creating the BEM geometry...
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<decorator-gen-92>", line 22, in make_bem_model
  File "/home/larsoner/python/mne-python/mne/bem.py", line 591, in make_bem_model
    surfaces = _surfaces_to_bem(surfaces, ids, conductivity, ico)
  File "/home/larsoner/python/mne-python/mne/bem.py", line 505, in _surfaces_to_bem
    surfs[si] = _ico_downsample(surf, ico)
  File "/home/larsoner/python/mne-python/mne/bem.py", line 382, in _ico_downsample
    raise RuntimeError('The source surface has a matching number of '
RuntimeError: The source surface has a matching number of triangles but ordering is wrong
```
But I can fix it:
```Python
>>> for key in ('inner_skull', 'outer_skull', 'outer_skin'):
...     rr, tris = mne.read_surface(f'{name}/bem/{key}_large.surf')
...     rr, tris = mne.decimate_surface(rr, tris, 20480, method='sphere')
...     mne.write_surface(f'{name}/bem/{key}.surf', rr, tris, overwrite=True)
>>> bem = mne.make_bem_model(name, subjects_dir='.', verbose=True)
Going from 5th to 4th subdivision of an icosahedron (n_tri: 20480 -> 5120)
Going from 5th to 4th subdivision of an icosahedron (n_tri: 20480 -> 5120)
Going from 5th to 4th subdivision of an icosahedron (n_tri: 20480 -> 5120)
outer skin  CM is  -0.37  -8.72  -0.69 mm
outer skull CM is   0.46 -18.62  14.80 mm
inner skull CM is   0.48 -18.83  15.32 mm
Checking that outer skull surface is inside outer skin  surface...
Checking that inner skull surface is inside outer skull surface...
Checking distance between outer skin  and outer skull surfaces...
Minimum distance between the outer skin  and outer skull surfaces is approximately    1.2 mm
Checking distance between outer skull and inner skull surfaces...
Minimum distance between the outer skull and inner skull surfaces is approximately    1.5 mm
Surfaces passed the basic topology checks.
Complete.
```
Is it possible that the surface files were not updated properly? Maybe this was an issue on d907822cdd50695838a7b03e9f50764862a83eb4 but won't be once I can download the latest `git-lfs` files?

**Comment by larsoner** [comment]
I just realized that I need to use / look https://github.com/christian-oreilly/infant_template_paper/releases, right?

**Comment by christian-oreilly** [comment]
That is right @larsoner Sorry for the confusion created by me not cleaning up behind myself :) The files you were trying to use are now removed.
